src/Entity/Book.php
<?php

namespace App\Entity;

use App\Repository\BookRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Form\Type\VichFileType;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass=BookRepository::class)
 * @Vich\Uploadable
 */
class Book
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @var string|null
     */
    private $img_cover;

    /**
     * @Vich\UploadableField(mapping="book_covers", fileNameProperty="img_cover")
     * @var File
     */
    private $folderImage;

    /**
     * @ORM\Column(type="datetime",  options={"default": "CURRENT_TIMESTAMP"})
     */
    private $updated_at;

    /**
     * @ORM\Column(type="date")
     */
    private $published_at;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $author;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_reserved;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $is_favorite;

    /**
     * @ORM\ManyToMany(targetEntity=Type::class, inversedBy="books", cascade={"persist"})
     */
    private $type;

    /**
     * @ORM\OneToMany(targetEntity=BookLoan::class, mappedBy="book")
     */
    private $bookLoans;

    public function __construct()
    {
        $this->type = new ArrayCollection();
        $this->bookLoans = new ArrayCollection();
        $this->is_reserved = false;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getImgCover(): ?string
    {
        return $this->img_cover;
    }

    public function setImgCover( ?string $img_cover): self
    {
        $this->img_cover = $img_cover;

        return $this;
    }


    /**
     * @return null|File
     */
    public function getFolderImage(): ?File
    {
        return $this->folderImage;
    }

    /**
     * @param File|null $folderImage
     */

    public function setFolderImage(?File $folderImage = null): void
    {
        $this->folderImage = $folderImage;

        if($folderImage){
            $this->updated_at = new \DateTime('now');
        }
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getPublishedAt(): ?\DateTimeInterface
    {
        return $this->published_at;
    }

    public function setPublishedAt(\DateTimeInterface $published_at): self
    {
        $this->published_at = $published_at;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getAuthor(): ?string
    {
        return $this->author;
    }

    public function setAuthor(string $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function getIsReserved(): ?bool
    {
        return $this->is_reserved;
    }

    public function setIsReserved(bool $is_reserved): self
    {
        $this->is_reserved = $is_reserved;

        return $this;
    }

    public function getIsFavorite(): ?bool
    {
        return $this->is_favorite;
    }

    public function setIsFavorite(bool $is_favorite): self
    {
        $this->is_favorite = $is_favorite;

        return $this;
    }

    /**
     * @return Collection|Type[]
     */
    public function getType(): Collection
    {
        return $this->type;
    }

    public function addType(Type $type): self
    {
        if (!$this->type->contains($type)) {
            $this->type[] = $type;
        }

        return $this;
    }

    public function removeType(Type $type): self
    {
        $this->type->removeElement($type);

        return $this;
    }

    /**
     * @return Collection|BookLoan[]
     */
    public function getBookLoans(): Collection
    {
        return $this->bookLoans;
    }

    public function addBookLoan(BookLoan $bookLoan): self
    {
        if (!$this->bookLoans->contains($bookLoan)) {
            $this->bookLoans[] = $bookLoan;
            $bookLoan->setBook($this);
        }

        return $this;
    }

    public function removeBookLoan(BookLoan $bookLoan): self
    {
        if ($this->bookLoans->removeElement($bookLoan)) {
            // set the owning side to null (unless already changed)
            if ($bookLoan->getBook() === $this) {
                $bookLoan->setBook(null);
            }
        }

        return $this;
    }

    public function __toString() : string
    {
        return $this->getTitle();
    }

}

src/Form/BookType.php
<?php

namespace App\Form;

use App\Entity\Book;
use App\Entity\Type;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\Validator\Constraints\Type as TypeConstraint;
use Vich\UploaderBundle\Form\Type\VichFileType;

class BookType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title', TextType::class,[
                'label'=>'Titre',
                'constraints' => [
                    new Length([
                        'min'=> 2,
                        'max'=>50,
                        'minMessage'=>'Le nom du livre est trop court',
                        'maxMessage'=>'Le nom du livre est trop long',
                        ]),
                    new TypeConstraint(['string'])
                ]
            ])
            ->add('author', TextType::class,[
                'label'=>'Auteur',
                'constraints'=>[
                    new Length([
                        'min'=>2,
                        'max'=>30,
                        'minMessage'=>'Le nom de l\'auteur est trop court',
                        'maxMessage'=>'Le nom de l\'auteur est trop long',
                        ]),
                    new TypeConstraint(['string'])
                ]
            ])
            ->add('published_at', DateType::class,[
                'label'=>'Date de publication',
                'widget'=>'single_text',
                'constraints'=>[
                    new NotBlank(['message'=>'La date de publication doit être renseignée']),
                    new TypeConstraint(['DateTimeInterface'])
                ]
            ])
            ->add('folderImage',VichFileType::class,[
                'label'=>'Image de couverture',
                'allow_delete' => false,
                'required' => false
            ])

            ->add('type', EntityType::class,[
                'class'=>Type::class,
                'choice_label'=>'name',
                'multiple'=>true,
                'expanded'=>true,
                'constraints' => [
                    new NotBlank(['message'=>'Le type du livre doit être renseigné'])
                ]

            ])
            ->add('is_favorite', CheckboxType::class,[
                'label'=>'Afficher le livre en coup de coeur',
                'required'=>false,

            ])
            ->add('description', TextareaType::class,[
                'label'=>'Description',
                'constraints' => [
                    new Length([
                        'min'=> 2,
                        'max'=>2500,
                        'minMessage'=>'La description est trop courte',
                        'maxMessage'=>'La description est trop longue',
                        ]),
                    new TypeConstraint(['string'])
                ]

            ])
            ->add('submit', SubmitType::class,[
                'label'=>'Enregistrer',
                'attr'=>[
                    'class'=>'w-100 mt-5 btn-primary'
                ]
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Book::class,
        ]);
    }
}

src/Controller/BookController.php
<?php

namespace App\Controller;

use App\Entity\Book;
use App\Entity\Type;
use App\Form\BookType;
use App\Form\TypeType;
use App\Repository\BookRepository;
use App\Repository\TypeRepository;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\Persistence\ObjectManager;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/dashboard/livres")
 */
class BookController extends AbstractController
{
    /**
     * @Route("/", name="book_index", methods={"GET"})
     */
    public function index(BookRepository $bookRepository, PaginatorInterface $paginator, Request $request): Response
    {
        $books = $paginator->paginate(
            $bookRepository->findAllByPaginationQuery(),
            $request->query->getInt('page', 1),
            5
        );

        return $this->render('book/index.html.twig', [
            'books' => $books
        ]);
    }

    /**
     * @Route("/nouveau-livre", name="book_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $book = new Book();
        $form = $this->createForm(BookType::class, $book);

        $type = new Type();
        $formType = $this->createForm(TypeType::class,$type);

        $form->handleRequest($request);
        $formType->handleRequest($request);

        if($formType->isSubmitted() && $formType->isValid()){
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($type);
            $entityManager->flush();

            return $this->redirectToRoute('book_new');

        }

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($book);
            $entityManager->flush();


            return $this->redirectToRoute('book_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('book/new.html.twig', [
            'book' => $book,
            'form' => $form,
            'formType'=>$formType
        ]);
    }

    /**
     * @Route("/{id}", name="book_show", methods={"GET"})
     */
    public function show(Book $book): Response
    {
        return $this->render('book/show.html.twig', [
            'book' => $book,
        ]);
    }

    /**
     * @Route("/{id}/modifier", name="book_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Book $book): Response
    {
        $form = $this->createForm(BookType::class, $book);
        $form->handleRequest($request);

        $type = new Type();
        $formType = $this->createForm(TypeType::class, $type);
        $formType->handleRequest($request);

        if ($formType->isSubmitted() && $formType->isValid()) {
            $this->getDoctrine()->getManager()->persist($type);
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('book_edit',[
                'id'=>$book->getId(),
            ] );
        }

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('book_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('book/edit.html.twig', [
            'book' => $book,
            'form' => $form,
            'formType'=>$formType
        ]);
    }

    /**
     * @Route("/{id}", name="book_delete", methods={"POST"})
     */
    public function delete(Request $request, Book $book): Response
    {
        if ($this->isCsrfTokenValid('delete'.$book->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($book);
            $entityManager->flush();
        }

        return $this->redirectToRoute('book_index', [], Response::HTTP_SEE_OTHER);
    }


}

templates/book/_delete_form.html.twig
<form method="post" action="{{ path('book_delete', {'id': book.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ book.id) }}">
    <button class="btn">Delete</button>
</form>

templates/book/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/book/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier {{ book.title }} | La Réserve de la Chapelle{% endblock %}

{% block body %}
<div class="container-fluid dashboard">
    <div class="row">
        {{ include ('_dashboard-navigation.html.twig') }}
        <div class="col-9 col-sm-10 col-xxl-11 pt-3 ps-3 ps-lg-5">
            {{ include ('_navigation.html.twig') }}

            <section class="mt-5 pt-5">
                <a class="text-uppercase fw-bold text-decoration-none" href="{{ path('book_index') }}"> &#60 Retourner aux livres</a>
                <h1 class="mt-5">Modifier {{ book.title | capitalize }}</h1>
            </section>

            <section class="row my5 me-lg-5 pt-5">
                <div class="col-lg-8">
                    {{ form_start(form) }}
                    <div class="row d-flex flex-column flex-sm-row justify-content-between">
                        <div class="col-12 col-md-5  me-sm-2">{{ form_row(form.title) }}</div>
                        <div class="col-12 col-md-5 ms-sm-2">{{ form_row(form.author) }}</div>
                    </div>
                    <div class="row d-flex flex-column flex-sm-row justify-content-between">
                        <div class="col-12 col-md-5  me-sm-2">{{ form_row(form.published_at) }}</div>
                        <div class="col-12 col-md-5 ms-sm-2">{{ form_row(form.folderImage) }}</div>
                    </div>
                    <div class="row d-flex flex-column flex-sm-row justify-content-between">
                        <div class="col-12 col-md-5  me-sm-2 book-type">
                            {{ form_row(form.type) }}
                            <button class="btn border border-2 border-info mb-4">
                                <a class="text-decoration-none text-info fw-light" data-bs-toggle="modal" data-bs-target="#modal1">
                                    + Ajouter une catégorie
                                </a>
                            </button>
                        </div>
                        <div class="col-12 col-md-5 ms-sm-2  ps-2 form-switch is-favorite">{{ form_row(form.is_favorite) }}</div>
                    </div>
                    {{ form_end(form) }}
                </div>
            </section>

            <!-- Modal -->
            <div class="modal fade" id="modal1" tabindex="-1" aria-labelledby="exampleModalLabel2" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered modal-lg">
                    <div class="modal-content px-5">
                        <div class="modal-header border-0 d-flex flex-column align-items-center mt-3">
                            <div class="d-flex flex-column align-items-center">
                                <figure>
                                    <img src="{{ asset('build/images/icon-book_type.svg') }}" alt="Icon de catégorie de livre" width="40" height="40">
                                </figure>
                                <h2 class="modal-title" id="exampleModalLabel">Nouvelle catégorie</h2>
                            </div>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>

                          <div class="modal-body px-5">
                            {{ form_start(formType) }}
                            {{ form_row(formType.name) }}
                            <button class="w-100 mb-5 mt-3 btn btn-primary connect-button" type="submit">Enregistrer</button>
                            {{ form_end(formType) }}
                        </div>
                    </div>
                </div>
            </div>


           {#  {{ include('book/_form.html.twig', {'button_label': 'Update'}) }}

            <a href="{{ path('book_index') }}">back to list</a>

            {{ include('book/_delete_form.html.twig') }}#}
        </div>
    </div>
</div>
{% endblock %}

templates/book/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter un nouveau livre | La Réserve de la Chapelle{% endblock %}

{% block body %}
<div class="container-fluid dashboard">
    <div class="row">
        {{ include ('_dashboard-navigation.html.twig') }}
        <div class="col-9 col-sm-10 col-xxl-11 pt-3 ps-3 ps-lg-5">
            {{ include ('_navigation.html.twig') }}

            <section class="mt-5 pt-5">
                <a class="text-uppercase fw-bold text-decoration-none" href="{{ path('book_index') }}"> &#60 Retourner aux livres</a>
                <h1 class="mt-5">Créer un nouveau livre</h1>
            </section>

            <section class="row my5 me-lg-5 pt-5">
                <div class="col-lg-8">
                    {{ form_start(form) }}
                    <div class="row d-flex flex-column flex-sm-row justify-content-between">
                        <div class="col-12 col-md-5  me-sm-2">{{ form_row(form.title) }}</div>
                        <div class="col-12 col-md-5 ms-sm-2">{{ form_row(form.author) }}</div>
                    </div>
                    <div class="row d-flex flex-column flex-sm-row justify-content-between">
                        <div class="col-12 col-md-5  me-sm-2">{{ form_row(form.published_at) }}</div>
                        <div class="col-12 col-md-5 ms-sm-2">{{ form_row(form.folderImage) }}</div>
                    </div>
                    <div class="row d-flex flex-column flex-sm-row justify-content-between">
                        <div class="col-12 col-md-5  me-sm-2 book-type">
                            {{ form_row(form.type) }}
                            <button class="mb-4 btn border border-2 border-info text-info fw-light" data-bs-toggle="modal" data-bs-target="#modal2">
                                + Ajouter une catégorie
                            </button>
                        </div>
                        <div class="col-12 col-md-5 ms-sm-2  ps-2 form-switch is-favorite">{{ form_row(form.is_favorite) }}</div>
                    </div>
                    {{ form_end(form) }}
                </div>
            </section>

            <!-- Modal -->
            <div class="modal fade" id="modal2" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered modal-lg">
                    <div class="modal-content px-5">
                        <div class="modal-header border-0 d-flex flex-column align-items-center mt-3">
                            <div class="d-flex flex-column align-items-center">
                                <figure>
                                    <img src="{{ asset('build/images/icon-book_type.svg') }}" alt="Icon de catégorie de livre" width="40" height="40">
                                </figure>
                                <h2 class="modal-title" id="exampleModalLabel">Nouvelle catégorie</h2>
                            </div>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>

                        <div class="modal-body px-5">
                            {{ form_start(formType) }}
                            {{ form_row(formType.name) }}
                            <button class="btn btn-primary connect-button w-100 text-uppercase mt-3 mb-5" type="submit">Enregistrer
                                {#  <a type="submit" id="book-type-add" class="text-white text-decoration-none" href="{{ path('book_new') }}">Enregistrer</a>#}
                            </button>
                            {{ form_end(formType) }}
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>

{% endblock %}

templates/book/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ book.title  }} | La Réserve de la Chapelle{% endblock %}

{% block body %}
<div class="container-fluid dashboard">
    <div class="row">
        {{ include ('_dashboard-navigation.html.twig') }}
        <div class="col-9 col-sm-10 col-xxl-11 pt-3 ps-3 ps-lg-5">
            {{ include ('_navigation.html.twig') }}

            <section class="mt-5 pt-5">
                <a class="text-uppercase fw-bold text-decoration-none ps-lg-5" href="{{ path('book_index') }}"> &#60 Retourner aux livres</a>
                <h1 class="mt-5 ps-5">Livre #{{ book.id }}</h1>
            </section>

            <section class="me-lg-5 ps-lg-5 d-flex flex-column flex-xxl-row align-items-center">
                <figure class="book-cover-show me-lg-5 rounded-4">
                    <img src="{{ vich_uploader_asset(book,'folderImage') }}" alt="Photo de couverture du livre" class="rounded-4 is-book-dashboard">
                    <div class="book-cover-info">
                        <p class="text-white fw-bold fs-3 text-end">{{ book.title |capitalize }}</p>
                        <p class="text-white fw-light text-end">{{ book.author | title }}</p>
                    </div>

                    {% if book.isFavorite %}
                        <svg class="float-start" width="44" height="44" viewBox="0 0 24 24" fill="#8887B9" xmlns="http://www.w3.org/2000/svg">
                        <path d="M20.16 5.00017C19.1 3.93737 17.6948 3.28871 16.1984 3.17134C14.7019 3.05397 13.2128 3.47563 12 4.36017C10.7277 3.4138 9.14402 2.98468 7.56795 3.1592C5.99188 3.33373 4.54047 4.09894 3.506 5.30075C2.47154 6.50256 1.93085 8.05169 1.99283 9.63618C2.05481 11.2207 2.71485 12.7228 3.84003 13.8402L10.05 20.0602C10.57 20.5719 11.2704 20.8588 12 20.8588C12.7296 20.8588 13.43 20.5719 13.95 20.0602L20.16 13.8402C21.3276 12.6654 21.983 11.0764 21.983 9.42017C21.983 7.76389 21.3276 6.1749 20.16 5.00017ZM18.75 12.4602L12.54 18.6702C12.4694 18.7415 12.3853 18.7982 12.2926 18.8368C12.1999 18.8755 12.1005 18.8954 12 18.8954C11.8996 18.8954 11.8002 18.8755 11.7075 18.8368C11.6148 18.7982 11.5307 18.7415 11.46 18.6702L5.25003 12.4302C4.46579 11.6285 4.02664 10.5516 4.02664 9.43017C4.02664 8.3087 4.46579 7.23182 5.25003 6.43017C6.04919 5.64115 7.127 5.19873 8.25003 5.19873C9.37306 5.19873 10.4509 5.64115 11.25 6.43017C11.343 6.52389 11.4536 6.59829 11.5755 6.64906C11.6973 6.69983 11.828 6.72596 11.96 6.72596C12.092 6.72596 12.2227 6.69983 12.3446 6.64906C12.4665 6.59829 12.5771 6.52389 12.67 6.43017C13.4692 5.64115 14.547 5.19873 15.67 5.19873C16.7931 5.19873 17.8709 5.64115 18.67 6.43017C19.4651 7.22132 19.9186 8.29236 19.9336 9.41385C19.9485 10.5353 19.5237 11.6181 18.75 12.4302V12.4602Z"/>
                        </svg>
                    {% endif %}

                </figure>
                <div class="col-xxl-8 d-flex flex-column ms-3 book-description-show">
                    <h2>{{ book.title | capitalize }}</h2>
                    <p class="fst-italic">par {{ book.author | title }}</p>
                    <p>Genre : {% for type in book.type %}{{ type.name | capitalize }} {% endfor %}</p>
                    <p class="fst-italic">Publié le {{ book.publishedAt ? book.publishedAt|date('d/m/Y') : '' }}</p>
                    <label>Description</label>
                    <div class="overflow-scroll">
                        <p>{{ book.description | nl2br }}</p>
                    </div>
                </div>
            </section>

            <section class="d-flex flex-column flex-lg-row justify-content-center my-3">
                {#  <a href="{{ path('book_index') }}">back to list</a>#}
                <form method="post" action="{{ path('book_delete', {'id': book.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');" class="me-xl-3 mt-2">
                    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ book.id) }}">
                    <button class="btn btn-danger text-white px-4 w-100">Supprimer</button>
                </form>
                <button class="btn btn-secondary ms-xl-3 px-5 mt-2">
                    <a class="text-white text-decoration-none" href="{{ path('book_edit', {'id': book.id}) }}">Modifier</a>
                </button>
            </section>


        </div>
    </div>
</div>
{% endblock %}

{#  }{% block body %}
    <h1>Book</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ book.id }}</td>
            </tr>
            <tr>
                <th>Title</th>
                <td>{{ book.title }}</td>
            </tr>
            <tr>
                <th>Img_cover</th>
                <td>{{ book.imgCover }}</td>
            </tr>
            <tr>
                <th>Updated_at</th>
                <td>{{ book.updatedAt ? book.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Published_at</th>
                <td>{{ book.publishedAt ? book.publishedAt|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ book.description }}</td>
            </tr>
            <tr>
                <th>Author</th>
                <td>{{ book.author }}</td>
            </tr>
            <tr>
                <th>Is_reserved</th>
                <td>{{ book.isReserved ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Is_favorite</th>
                <td>{{ book.isFavorite ? 'Yes' : 'No' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('book_index') }}">back to list</a>

    <a href="{{ path('book_edit', {'id': book.id}) }}">edit</a>

    {{ include('book/_delete_form.html.twig') }}
{% endblock %}#}