src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $firstname;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $lastname;

    /**
     * @ORM\Column(type="date")
     */
    private $date_birth;

    /**
     * @ORM\Column(type="text")
     */
    private $address;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_confirmed;

    /**
     * @ORM\OneToMany(targetEntity=BookLoan::class, mappedBy="user")
     */
    private $bookLoans;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_inscription;

    //At creation, all new User are not confirmed yet. Only the employe can set is_confirmed into true
    public function __construct(){
        $this->is_confirmed = false;
        $this->date_inscription = new \DateTime('now');
        $this->bookLoans = new ArrayCollection();
    }

    public function __toString(){
        return $this->getFirstname();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getDateBirth(): ?\DateTimeInterface
    {
        return $this->date_birth;
    }

    public function setDateBirth(\DateTimeInterface $date_birth): self
    {
        $this->date_birth = $date_birth;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getIsConfirmed(): ?bool
    {
        return $this->is_confirmed;
    }

    public function setIsConfirmed(bool $is_confirmed): self
    {
        $this->is_confirmed = $is_confirmed;

        return $this;
    }

    /**
     * @return Collection|BookLoan[]
     */
    public function getBookLoans(): Collection
    {
        return $this->bookLoans;
    }

    public function addBookLoan(BookLoan $bookLoan): self
    {
        if (!$this->bookLoans->contains($bookLoan)) {
            $this->bookLoans[] = $bookLoan;
            $bookLoan->setUser($this);
        }

        return $this;
    }

    public function removeBookLoan(BookLoan $bookLoan): self
    {
        if ($this->bookLoans->removeElement($bookLoan)) {
            // set the owning side to null (unless already changed)
            if ($bookLoan->getUser() === $this) {
                $bookLoan->setUser(null);
            }
        }

        return $this;
    }

    public function getDateInscription(): ?\DateTimeInterface
    {
        return $this->date_inscription;
    }

    public function setDateInscription(\DateTimeInterface $date_inscription): self
    {
        $this->date_inscription = $date_inscription;

        return $this;
    }

}

src/Controller/DashboardController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Repository\UserRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class DashboardController extends AbstractController
{
    /**
     * @Route("/dashboard", name="dashboard")
     */
    public function index(EntityManagerInterface $entityManager): Response
    {
        //$users = $entityManager->getRepository(User::class)->findAll();
        $users = $entityManager->getRepository(User::class)->findBy(['is_confirmed' => false]);
        return $this->render('dashboard/index.html.twig',[
            'users'=>$users
            ]);
    }

    /**
     * @Route("/dashboard/adherent/{id}/confirmer", name="user_approve",  methods={"POST"})
     * @param User $user
     * @param EntityManagerInterface $entityManager
     * @return Response
     */
    public function approveUser(User $user, EntityManagerInterface $entityManager) : Response
    {
        $userUpdate = $user->setRoles(["ROLE_SUBSCRIBER"])
            ->setIsConfirmed(true)
        ;

        $entityManager->persist($userUpdate);
        $entityManager->flush();

        return $this->json([
            'userId'=>$user->getId()
        ],200);
    }

}

templates/dashboard/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Dashboard | La Réserve de la Chapelle{% endblock %}

{% block body %}

    <div class="container-fluid dashboard">
        <div class="row">
            {{ include ('_dashboard-navigation.html.twig') }}
            <div class="col-9 col-sm-10 col-xxl-11 pt-3 ps-3 ps-lg-5">
                {{ include ('_navigation.html.twig') }}

                {# TITLE OF DASHBOARD]#}
                <section class="mt-5 pt-5">
                    <h1 class="mt-5">Bonjour {{ app.user.firstname | capitalize }}</h1>
                    <div class="d-flex justify-content-start">
                        <figure class="me-2"><img src="{{ asset('build/images/icon-info.svg') }}" alt="Icon d'information" width="24" height="24"></figure>
                        <p>Il y a <span id="count-js" class="fw-bold">{{ users|length }}</span> compte{% if users|length>1 %}s{% endif %} à confirmer aujourd'hui</p>
                    </div>
                </section>

                <section class="mt-5 pt-5">
                    <div class="table-responsive">
                        <table class="table">
                            <thead>
                            <tr>
                                <th class="fw-bold border-0">Nom</th>
                                <th class="fw-bold border-0">Prénom</th>
                                <th class="fw-bold border-0">Date d'inscription</th>
                                <th class="fw-bold border-0">Statut</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for user in users %}
                                <tr id="tr-user-{{ user.id }}" class="animation">
                                    <td class="border-0">{{ user.lastname | capitalize }}</td>
                                    <td class="border-0">{{ user.firstname | capitalize }}</td>
                                    <td class="border-0">{{ user.dateInscription|date('d/m/Y - H:s')}}</td>
                                    <td class="border-0">{% if user.isConfirmed == false %}En attente{% endif %}</td>
                                    <td class="border-0">
                                        <div class="form-check">
                                            <input class="form-check-input js-checked" type="checkbox" id="defaultCheck1" aria-label="default" data-url="{{ path('user_approve',{'id':user.id}) }}">
                                        </div>
                                    </td>

                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>

                    <div class="position-fixed bottom-0 end-0 p-3" style="z-index: 11">
                        <div class="toast-container">
                            {% for user in users %}
                            <div id="toast-user-{{ user.id }}" class="toast animation" role="alert" aria-live="assertive" aria-atomic="true">
                                <div class="toast-header align-items-start">
                                    <figure class="m-0">
                                      <img src="{{ asset('build/images/icon-user-confirmed.svg') }}" alt="Icon de confirmation de compte" width="22" height="22">
                                    </figure>
                                    <strong class="ms-3 me-auto">Compte confirmé</strong>
                                    {#  <small class="text-muted">just now</small>#}
                                    <button type="button" class="btn-close me-1" data-bs-dismiss="toast" aria-label="Close"></button>
                                </div>
                                <div class="toast-body">
                                    <p class="mb-0">Le compte de <span class="fw-bold text-primary">{{ user.firstname | capitalize }} {{ user.lastname | capitalize }}</span> a été confirmé</p>
                                </div>
                            </div>
                            {% endfor %}


                        </div>
                    </div>


                </section>



            </div>
        </div>
    </div>
{% endblock %}

{% block javascripts %}
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
    <script>

        window.onload = ()=> {

            function onChangeCheckApprove(){
                const url = this.getAttribute('data-url');

                axios.post(url).then ( (response) =>{
                    let tr =  document.getElementById('tr-user-'+response.data.userId);
                    let toast = document.getElementById('toast-user-'+response.data.userId);
                    let count = document.getElementById('count-js').textContent;
                    document.getElementById('count-js').textContent = parseInt(count) - 1;

                    //REMOVE THE USER FROM LIST
                    tr.classList.add('fadeOutRight');
                    setTimeout(function(){
                        tr.style.display ='none';
                    }, 3000);


                    //SHOW TOAST OF CONFIRMATION
                    toast.classList.add('show', 'slideInUp');
                    //...AND HIDE
                    setTimeout(function(){
                        toast.classList.add('fadeOut');
                    }, 3000);
                    setTimeout(function(){
                        toast.classList.remove('show','slideInUp', 'fadeOut');
                    }, 4200);
                }).catch(function(error){
                    console.log(error);
                })
            }

            document.querySelectorAll('input.js-checked').forEach((checkedItem) =>{
                checkedItem.addEventListener('change', onChangeCheckApprove)
            })

        };

    </script>
{% endblock %}