src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $firstname;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $lastname;

    /**
     * @ORM\Column(type="date")
     */
    private $date_birth;

    /**
     * @ORM\Column(type="text")
     */
    private $address;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_confirmed;

    /**
     * @ORM\OneToMany(targetEntity=BookLoan::class, mappedBy="user")
     */
    private $bookLoans;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_inscription;

    //At creation, all new User are not confirmed yet. Only the employe can set is_confirmed into true
    public function __construct(){
        $this->is_confirmed = false;
        $this->date_inscription = new \DateTime('now');
        $this->bookLoans = new ArrayCollection();
    }

    public function __toString(){
        return $this->getFirstname();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getDateBirth(): ?\DateTimeInterface
    {
        return $this->date_birth;
    }

    public function setDateBirth(\DateTimeInterface $date_birth): self
    {
        $this->date_birth = $date_birth;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getIsConfirmed(): ?bool
    {
        return $this->is_confirmed;
    }

    public function setIsConfirmed(bool $is_confirmed): self
    {
        $this->is_confirmed = $is_confirmed;

        return $this;
    }

    /**
     * @return Collection|BookLoan[]
     */
    public function getBookLoans(): Collection
    {
        return $this->bookLoans;
    }

    public function addBookLoan(BookLoan $bookLoan): self
    {
        if (!$this->bookLoans->contains($bookLoan)) {
            $this->bookLoans[] = $bookLoan;
            $bookLoan->setUser($this);
        }

        return $this;
    }

    public function removeBookLoan(BookLoan $bookLoan): self
    {
        if ($this->bookLoans->removeElement($bookLoan)) {
            // set the owning side to null (unless already changed)
            if ($bookLoan->getUser() === $this) {
                $bookLoan->setUser(null);
            }
        }

        return $this;
    }

    public function getDateInscription(): ?\DateTimeInterface
    {
        return $this->date_inscription;
    }

    public function setDateInscription(\DateTimeInterface $date_inscription): self
    {
        $this->date_inscription = $date_inscription;

        return $this;
    }

}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\RegisterType;
use App\Repository\UserRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/dashboard/utilisateur")
 */
class UserController extends AbstractController
{
    /**
     * @Route("/", name="user_index", methods={"GET"})
     */
    public function index(UserRepository $userRepository): Response
    {
        $users = $userRepository->findByRoles();
        return $this->render('user/index.html.twig', [
            'users'=>$users
        ]);
    }

    /**
     * @Route("/ajouer-un-employe", name="user_new", methods={"GET","POST"})
     */
    public function new(Request $request, UserPasswordHasherInterface $hasher, EntityManagerInterface $entityManager): Response
    {
        $user = new User();
        $form = $this->createForm(RegisterType::class, $user);
        $form->remove('submit');

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $password = $hasher->hashPassword($user, $user->getPassword());
            $user->setPassword($password);
            $user->setIsConfirmed(true);

            $entityManager->persist($user);
            $entityManager->flush();

            return $this->redirectToRoute('user_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('user/new.html.twig', [
            'user' => $user,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="user_show", methods={"GET"})
     */
    public function show(User $user): Response
    {
        return $this->render('user/show.html.twig', [
            'user' => $user,
        ]);
    }

    /**
     * @Route("/{id}/modifier", name="user_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, User $user): Response
    {
        $form = $this->createForm(RegisterType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('user_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('user/edit.html.twig', [
            'user' => $user,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="user_delete", methods={"POST"})
     */
    public function delete(Request $request, User $user): Response
    {
        if ($this->isCsrfTokenValid('delete'.$user->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($user);
            $entityManager->flush();
        }

        return $this->redirectToRoute('user_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/user/_delete_form.html.twig
<form method="post" action="{{ path('user_delete', {'id': user.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user.id) }}">
    <button class="btn">Delete</button>
</form>

templates/user/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/user/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier {{ user.firstname }} {{ user.lastname }} | La Réserve de la Chapelle{% endblock %}

{% block body %}
<div class="container-fluid dashboard">
    <div class="row">
        {{ include ('_dashboard-navigation.html.twig') }}
        <div class="col-9 col-sm-10 col-xxl-11 pt-3 ps-3 ps-lg-5">
            {{ include ('_navigation.html.twig') }}

            <section class="mt-5 pt-5">
                <a class="text-uppercase fw-bold text-decoration-none" href="{{ path('user_index') }}"> &#60 Retourner aux employés</a>
                <h1 class="mt-5">Modifier {{ user.firstname }} {{ user.lastname }}</h1>
            </section>

            <section class="row my5 me-lg-5 pt-5">
                <div class="col-lg-8">
                    {{ form_start(form) }}
                    <div class="row d-flex flex-column flex-sm-row justify-content-between">
                        <div class="col-12 col-md-5  me-sm-2">{{ form_row(form.firstname) }}</div>
                        <div class="col-12 col-md-5 ms-sm-2">{{ form_row(form.lastname) }}</div>
                    </div>
                    <div class="row">
                        <div class="col-12 col-md-5  me-sm-2">{{ form_row(form.address) }}</div>
                    </div>
                    <div class="row d-flex flex-column flex-sm-row justify-content-between">
                        <div class="col-12 col-md-5  me-sm-2">{{ form_row(form.date_birth) }}</div>
                        <div class="col-12 col-md-5 ms-sm-2">{{ form_row(form.roles) }}</div>
                    </div>
                    {{ form_rest(form) }}
                    <button class="w-100 mb-5 mt-3 btn btn-primary connect-button text-uppercase" type="submit">Modifier</button>
                    {{ form_end(form) }}
                </div>
            </section>


        </div>
    </div>
</div>
{% endblock %}




    {# <h1>Edit User</h1>

    {{ include('user/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('user_index') }}">back to list</a>

    {{ include('user/_delete_form.html.twig') }}
{% endblock %}
#}

templates/user/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter un nouvel employé | La Réserve de la Chapelle{% endblock %}

{% block body %}
<div class="container-fluid dashboard">
    <div class="row">
        {{ include ('_dashboard-navigation.html.twig') }}
        <div class="col-9 col-sm-10 col-xxl-11 pt-3 ps-3 ps-lg-5">
            {{ include ('_navigation.html.twig') }}

            <section class="mt-5 pt-5">
                <a class="text-uppercase fw-bold text-decoration-none" href="{{ path('user_index') }}"> &#60 Retourner aux employés</a>
                <h1 class="mt-5">Créer un nouvel employé</h1>
            </section>

            <section class="row my5 me-lg-5 pt-5">
                <div class="col-lg-8">
                    {{ form_start(form) }}
                    <div class="row d-flex flex-column flex-sm-row justify-content-between">
                        <div class="col-12 col-md-5  me-sm-2">{{ form_row(form.firstname) }}</div>
                        <div class="col-12 col-md-5 ms-sm-2">{{ form_row(form.lastname) }}</div>
                    </div>

                    <div class="w-100 me-sm-2">{{ form_row(form.address) }}</div>

                    <div class="row d-flex flex-column flex-sm-row justify-content-between">
                        <div class="col-12 col-md-5  me-sm-2">{{ form_row(form.date_birth) }}</div>
                        <div class="col-12 col-md-5 ms-sm-2">{{ form_row(form.roles) }}</div>
                    </div>

                    <div class="w-100  me-sm-2">{{ form_row(form.email) }}</div>

                    <div class="w-100  me-sm-2">{{ form_row(form.password) }}</div>

                    <button class="btn btn-primary connect-button w-100 text-uppercase mt-3 mb-5 text-uppercase" type="submit">Enregistrer
                    </button>

                    {{ form_end(form) }}
                </div>
            </section>

        </div>
    </div>
</div>

{% endblock %}

templates/user/show.html.twig
{% extends 'base.html.twig' %}
{% block title %}{{ user.firstname }} {{ user.lastname}} | La Réserve de la Chapelle{% endblock %}

{% block body %}
<div class="container-fluid dashboard">
    <div class="row col">
        {{ include ('_dashboard-navigation.html.twig') }}
        <div class="col mt-3 ms-5">
            {{ include ('_navigation.html.twig') }}

            <section class="mt-5 pt-5">
                <a class="text-uppercase fw-bold text-decoration-none ps-5" href="{{ path('user_index') }}"> &#60 Retourner aux employés</a>
                <h1 class="mt-5 ps-5">{{ user.firstname }} {{ user.lastname }}</h1>
            </section>

            <section class="me-5 ps-5">
                <table class="table">
                    <tbody>
                    <tr>
                        <th>Email</th>
                        <td>{{ user.email }}</td>
                    </tr>
                    <tr>
                        <th>Roles</th>
                        <td>{% for role in user.roles  %}
                            {% if role == 'ROLE_ADMIN' %}Admin{% elseif role == 'ROLE_EMPLOYE' %}Employé{% endif %}
                            {% endfor %}</td>
                    </tr>
                    <tr>
                        <th>Prénom</th>
                        <td>{{ user.firstname }}</td>
                    </tr>
                    <tr>
                        <th>Nom de famille</th>
                        <td>{{ user.lastname }}</td>
                    </tr>
                    <tr>
                        <th>Date de naissance</th>
                        <td>{{ user.dateBirth ? user.dateBirth|date('Y-m-d') : '' }}</td>
                    </tr>
                    <tr>
                        <th>Addresse</th>
                        <td>{{ user.address }}</td>
                    </tr>
                    <tr>
                        <th>Date d'inscription</th>
                        <td>{{ user.dateInscription ? user.dateInscription|date('Y-m-d H:i:s') : '' }}</td>
                    </tr>
                    </tbody>
                </table>
            </section>

        </div>
    </div>
</div>
{% endblock %}